### ISSUE TITLE
General Notes

### ISSUE THREAD

**Issue by Mahmoud-Ahmad2** [GSG-G11/Feedbacky-Nabil-Maram#17]
Great job!! 👑
You did a Wonderfull job 💪 🥳
I don't have the words to till you how much I loved your job, But i have one comment:
1- You added all the names in the database but you didn't use it to create the element in the front .

**Comment by nabilramy** [comment]
i could have done that but  i wanted to minimize the use of dom as Abdallah mentioned 💯
